name: Deploy React App to VM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DEPLOY_DIR: '~/testing-github-actions'  # Change to your path
  SCREEN_NAME: 'testing-githubActions'  # Your screen session name
  NODE_ENV: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "Host *" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config

    - name: Deploy React App
      run: |
        REPO_URL="https://${{ secrets.GITHUB_PAT }}@github.com/${{ github.repository }}.git"
        
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd ~/testing-github-actions
        
        echo "Updating existing repository..."
        git fetch origin
        git reset --hard origin/main
        git clean -fd
        
        echo "Installing dependencies..."

        cd ReactJs-Application

        npm i
        npm run build
        
        if screen -list | grep -q "$SCREEN_NAME"; then
          screen -S $SCREEN_NAME -X stuff $'\003'
          sleep 3
          screen -S $SCREEN_NAME -X quit
          sleep 1
        fi
        
        npm run start
        
        echo "✅ React app deployed and running in screen session: $SCREEN_NAME"
        EOF