name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            screen -S funddrama -X quit
            screen -dmS funddrama
            screen -S funddrama -X stuff "cd /path/to/your/project$(printf \\r)"
            screen -S funddrama -X stuff "git pull https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/your-repo/your-project.git$(printf \\r)"
            screen -S funddrama -X stuff "npm install$(printf \\r)"
            screen -S funddrama -X stuff "npm run build$(printf \\r)"
            screen -S funddrama -X stuff "npm run start$(printf \\r)"
          EOF
