name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into server
      run: ssh -o StrictHostKeyChecking=no -i ./tensorlabs_azure.pem azureuser@40.90.163.170 'true'

    - name: Pull latest code
      run: |
        ssh -o StrictHostKeyChecking=no -i ./tensorlabs_azure.pem azureuser@40.90.163.170 << 'EOF'
          git pull https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/<username>/<repo>.git
        EOF
