name: Deploy React App to VM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DEPLOY_DIR: '/var/www/my-react-app'  # Change to your path
  SCREEN_NAME: 'testing-githubActions'  # Your screen session name
  NODE_ENV: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        # Disable host key checking (not recommended for production)
        config: |
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null

    - name: Deploy React App
      run: |
        REPO_URL="https://${{ secrets.USER_PAT }}@github.com/${{ github.repository }}.git"
        
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        mkdir -p $DEPLOY_DIR || exit 1
        cd $DEPLOY_DIR
        
        if [ -d .git ]; then
          git reset --hard
          git clean -fd
          git pull origin main
        else
          git clone $REPO_URL .
        fi
        
        npm ci
        npm run build
        
        if screen -list | grep -q "$SCREEN_NAME"; then
          screen -S $SCREEN_NAME -X stuff $'\003'
          sleep 3
          screen -S $SCREEN_NAME -X quit
          sleep 1
        fi
        
        cd build
        screen -dmS $SCREEN_NAME serve -s . -l 3000
        
        echo "✅ React app deployed and running in screen session: $SCREEN_NAME"
        EOF