name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            # Quit existing screen session if any
            screen -S funddrama -X quit || true

            # Start a new screen session
            screen -dmS funddrama

            # Change to the project directory within the screen session
            screen -S funddrama -X stuff "cd fund-the-drama && printf \\r"
            sleep 2

            # Pull latest changes
            screen -S funddrama -X stuff "git pull https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/tensorlabs-io/fund-the-drama.git && printf \\r"
            sleep 2

            # Install dependencies
            screen -S funddrama -X stuff "npm install && printf \\r"
            sleep 2

            # Build the project
            screen -S funddrama -X stuff "npm run build && printf \\r"
            sleep 2

            # Start the project
            screen -S funddrama -X stuff "npm run start && printf \\r"
            sleep 2

            # Check if the npm run start command was sent
            screen -ls
          EOF
